### ISSUE TITLE
Hydra faces

### ISSUE THREAD

**Issue by jinnovation** [wasamasa/gotham-theme#14]
[FYI](https://github.com/abo-abo/hydra).

I can look into this if no one else beats me to it.

**Comment by wasamasa** [comment]
Hehe, this should be a good demonstration why the choice to name the head types after colors is idiotic. I do have red, blue, teal, but no pink or whatever shade of red amaranth is supposed to be. Ideas what existing shade those two should be?

**Comment by jinnovation** [comment]
Agreed; definitely believe that it's a terrible and contrived idea to associate behavior with colors that in themselves have next to no relation to those behaviors themselves.

My first instinct is to associate hydra's "pink" with gotham's "orange" and hydra's "amaranth" with gotham's "magenta," as those color pairs seem about as analogous that we can get without outright defining new color variables within the theme. I will be the first to admit that these pairing choices are not ideal.

**Comment by wasamasa** [comment]
OK, that sounds sensible enough for me.
