### ISSUE TITLE
Fantastic job

### ISSUE THREAD

**Issue by norbertklar** [wasamasa/gotham-theme#17]
You did a fantastic job! I'm really enjoying this theme(That's Go programming language in the pictures)!

![screenshot_2015-07-10_18-56-15](https://cloud.githubusercontent.com/assets/9632419/8624089/a25b7b7a-2735-11e5-9501-c61edd1c4682.png)

![screenshot_2015-07-10_18-57-38](https://cloud.githubusercontent.com/assets/9632419/8624090/a61ff812-2735-11e5-97f9-f112442b14f6.png)

![screenshot_2015-07-10_18-58-41](https://cloud.githubusercontent.com/assets/9632419/8624091/a8ab17d8-2735-11e5-9f2b-67f43e5ce35f.png)

**Comment by wasamasa** [comment]
Thanks, I'll add your screenshots to the README.
