### ISSUE TITLE
Use term face instead of term-default-fg-color and term-default-bg-color

### ISSUE THREAD

**Issue by IvanMalison** [wasamasa/gotham-theme#20]
term-default-fg-color is now obsolete and does not seem to have any effect

Also the convention seems to be to set the foreground and the background to nil and let people set their colors with the shell.

**Comment by wasamasa** [comment]
Hm, considering how I have convenience helpers there that only set up a face by that name, these lines you've removed shouldn't have had any effect at all, given how `term-default-fg-color` and `term-default-bg-color` are variables.  However this also means that there is no need for the theme to customize the `term` face either because it is set to `nil` for both fore- and background...

**Comment by IvanMalison** [comment]
> Hm, considering how I have convenience helpers there that only set up a face by that name, these lines you've removed shouldn't have had any effect at all, given how term-default-fg-color and term-default-bg-color are variables.

Yes, the lines have no effect

>However this also means that there is no need for the theme to customize the term face either because it is set to nil for both fore- and background...

Sorry what? The line I added definitely has an effect.

Without:
![screen shot 2015-11-17 at 2 38 37 am](https://cloud.githubusercontent.com/assets/1246619/11209292/12409e2a-8cd5-11e5-90dc-9e7a849c5b0b.png)

With:
![screen shot 2015-11-17 at 2 39 43 am](https://cloud.githubusercontent.com/assets/1246619/11209300/1b92df9c-8cd5-11e5-8b60-bebbf7e26cd1.png)

I need to investigate to see if something else in my configuration is having an effect here, but at the very least this line makes the theming more robust.

**Comment by wasamasa** [comment]
On 11/17/15 at 02:45am, IvanMalison wrote:
> Sorry what? The line I added definitely has an effect.

To quote the sources:

```elisp
(defcustom term-default-fg-color nil
  "If non-nil, default color for foreground in Term mode."
  :group 'term
  :type '(choice (const nil) (string :tag "color")))
(make-obsolete-variable 'term-default-fg-color "use the face `term' instead."
                        "24.3")

(defcustom term-default-bg-color nil
  "If non-nil, default color for foreground in Term mode."
  :group 'term
  :type '(choice (const nil) (string :tag "color")))
(make-obsolete-variable 'term-default-bg-color "use the face `term' instead."
                        "24.3")

(defface term
  `((t
     :foreground ,term-default-fg-color
     :background ,term-default-bg-color
     :inherit default))
  "Default face to use in Term mode."
  :group 'term)
```

Looks to me like `:foreground` and `:background` are set to `nil` and the face does otherwise inherit from the default face.  Which is the same as your change.  Which also means your change would be a no-op and rather confuse people reading this.

**Comment by IvanMalison** [comment]
That assumes that the term face has not taken on some other value because it was assigned to elsewhere which does not seem like a good assumption to me.

Perhaps I misunderstood the original code, but it seemed to me that the intention was to set a PARTICULAR value for the foreground and background colors for term mode.

Explicitly setting it the values to nil happens to have the same effect as setting particular values because it allows the colors of the theme to pass through. If a value is set it will take precedence.

I can see an argument that you would like custom overrides that are set BEFORE the theme is applied to be allowed, but it is definitely not true that the line is necessarily a no op.

**Comment by wasamasa** [comment]
That aside, `nil` isn't a valid value in this context anyway.  It should be `unspecified`.  It's hardly a single theme's responsibility though to fix this kind of thing...
