### ISSUE TITLE
better support for hl-line-mode

### ISSUE THREAD

**Issue by rafaelleru** [wasamasa/gotham-theme#55]
I'm using global-hl-line mode and the color of hilight is the same as color of selected text wich is alittle confused.
here it's a screenshot with no selceted text:
![screenshot_20170319_205149](https://cloud.githubusercontent.com/assets/6851409/24084202/05796dc4-0ce6-11e7-9e68-290136107f89.png)
And here with selected text:
![screenshot_20170319_205211](https://cloud.githubusercontent.com/assets/6851409/24084206/0ea314d6-0ce6-11e7-9cbe-4dda2b9ea0aa.png)

**Comment by wasamasa** [comment]
That doesn't look correct.  Here's how it looks for me in a minimal session:

![](http://i.imgur.com/bVUfV6T.png)

Make sure you don't have any other themes enabled (with `M-x disable-theme`).

**Comment by rafaelleru** [comment]
Yes sorry, I forgot to disable my solarized theme, thanks.
