### ISSUE TITLE
Improve diff-refine-* faces

### ISSUE THREAD

**Issue by stakemori** [wasamasa/gotham-theme#68]
I use magit with `(setq magit-diff-refine-hunk t)`. With this configuration, magit uses `diff-refine-hunk` when showing diff. But with this theme, there seems to be no difference between `(setq magit-diff-refine-hunk t)` and `(setq magit-diff-refine-hunk nil)`. 

Please consider to improve faces `diff-refine-added`, `diff-refine-changed` and `diff-refine-removed`. For example with `:inverse-video t`, I see a difference.

**Comment by wasamasa** [comment]
Thanks for the hint, I didn't know about this Magit option.
