### ISSUE TITLE
Change here-doc color to be more subtle 

### ISSUE THREAD

**Issue by tracphil** [wasamasa/gotham-theme#71]
First, this is a fantastic theme. It is very much appreciated. 

Is it possible to change the colors of here-doc statements color to be more subtle and with more pastel'y like the rest  of the theme?

![gotham-theme](https://i.imgur.com/EkWbuP0.png)

I don't know a lot about Emacs but my cobbled together configuration is at https://github.com/tracphil/.emacs.d. It is quite possible that the bright yellow and what looks like bold things are of my own doing and I just don't know any better.

**Comment by wasamasa** [comment]
This color is part of the theme, just like the rest of them.  If you put point on that text and use `M-x customize-face`, you can customize how it looks like for you.

**Comment by tracphil** [comment]
@wasamasa Thank you!

For others that might wish to do the same thing, this is how I implemented it in the end:

```lisp
(use-package gotham-theme
  :ensure t
  :config
  (load-theme 'gotham t)
  (custom-theme-set-faces
   'gotham
   '(sh-heredoc ((t (:foreground "light sea green" :weight normal))))
   )
  )
```
